# [START django_app]
runtime: python39

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

instance_class: B1

basic_scaling:
 max_instances: 20
 idle_timeout: 1m

# automatic_scaling:
#   min_idle_instances: 0
#   max_idle_instances: 0
#   min_instances: 0
#   max_instances: 20
#   max_concurrent_requests: 20    # default: 10, maximum: 80
  # target_cpu_utilization: 0.5   # range - 0.5 to 0.95
#  target_throughput_utilization: 0.5


#  min_pending_latency: 30ms  # lower the value --> quicker: can be set to zero
#max_pending_latency: automatic

# [END django_app]

#max_instances
#min_instances
#max_idle_instances
#min_idle_instances
#target_cpu_utilization
#target_throughput_utilization
#max_concurrent_requests
#max_pending_latency
#min_pending_latency
